### ISSUE TITLE
Grafana

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#195]
## What

Add [Grafana](https://grafana.com/) to make dashboards for Prometheus.

## How

- Prepare a container image for Grafana
- Deploy Grafana with Argo CD
- Configure Grafana to visualize Prometheus metrics
- Expose Grafana UI on the Internet restricting IP addresses
- Create IngressRoute for Grafana
## Checklist

- [x] Finish implentation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions
