### ISSUE TITLE
Monitoring by VictoriaMetrics

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#201]
old epic name: Long-term storage for Prometheus

## Description

Choose and deploy durable persistent storage for Prometheus.
Also, persist silence status of Alertmanager.

## Initiative / Motivation

The local storage of Prometheus is limited to a single node.
The default configuration is to keep metrics for only 15 days.
Ref: https://prometheus.io/docs/prometheus/latest/storage/

To keep metrics longer, we need to have durable storage for Prometheus.

Possible options are:
- [Cortex](https://github.com/cortexproject/cortex)
- [Remote storages](https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage)
- Local storage on Ceph RBD
    - Is Prometheus need to be a `StatefulSet` in this case?
- [Thanos + Object storage](https://github.com/improbable-eng/thanos)
- [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics)
- Cloud storage such as [Grafana Cloud](https://grafana.com/cloud#features)

These slides compare some of these solutions: https://promcon.io/2019-munich/slides/remote-write-storage-wars.pdf

When alertmanager Pod is recreated, silence status is cleared.
This is quite annoying, so keep the status.

## Scope and goal

- Metrics stored in Prometheus should be kept at least 1 year.
- The storage must be durable against a single server failure.
- Multi-tenancy for Neco users.
- The storage must be operated declaratively with the mechanism of the operator.

Non-goals:
- Durability for Alertmanager

## Definition of ready

- [x] The epic owner is assigned.
- [x] Initiatives and scopes are clearly stated.
- [x] Feasibility is proved by PoC or scrutiny.
- [x] All necessary issues that complete this epic are created.
- [x] At least three people agree to make this ready.

**Comment by umezawatakeshi** [comment]
shared cluster is splitted to #1320
