### ISSUE TITLE
Data backup system for VictoriaMetrics, Loki, and Tempo

### ISSUE THREAD

**Issue by umezawatakeshi** [cybozu-go/neco#2080]
## Description

Establish a data backup system in case of Ceph failure.

## Initiative / Motivation

The current Rook/Ceph subsystem in Neco cluster is not very trustable according to CSA team. They said that each Rook/Ceph user should establish a data backup system.

## Technical information

- [vmbackup](https://docs.victoriametrics.com/vmbackup.html), the official backup tool for VictoriaMetrics
  - We do not use [vmbackupmanager](https://docs.victoriametrics.com/vmbackupmanager.html) for now. It is an enterprise paid feature.
- [Enable versioning on buckets](https://docs.aws.amazon.com/AmazonS3/latest/userguide/manage-versioning-examples.html) and [Setting lifecycle configuration on a bucket](https://docs.aws.amazon.com/AmazonS3/latest/userguide/how-to-set-lifecycle-configuration-intro.html) (Amazon S3 documents) 
  - Loki and Tempo do not provide backup tools and Ceph RGW does not support snapshot. We have to create timestamp-strict backup tool for S3-compatible storage.

## Scope and goal

Establish the following with **minimum effort**

- Data backup system
- Restoring procedure

### non-goal

- The failure of the underlying storage (SSD or HDD themselves) is not cared. Just prepare for Rook/Ceph failure.
- This epic targets VictoriaMetrics, Loki, and Tempo. It does not target session recording of Teleport because it is not managed by Monitoring Team but by Network Team.
  Of course, Network Team may establish a data backup system for Teleport by using outputs of this epic.

## Definition of ready

- [x] The epic owner is assigned.
- [x] Initiatives and scopes are clearly stated.
- [x] Feasibility is proved by PoC or scrutiny.
- [x] All necessary issues that complete this epic are created.
- [x] At least three people (the epic owner and two other people) agree on making this ready.

**Comment by umezawatakeshi** [comment]
It was decided that no backup is required. This epic is abandoned.
