### ISSUE TITLE
Development environment for Neco users

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#211]
## Description

Provide a way to prepare development environments for Neco users

## Initiative / Motivation

Application developers that are willing to run their apps on Neco need
fully-constructed Neco data center on their GCP projects.

GCP projects may be either personal one or shared with team members.

A setup tool for such GCP projects that prepares fully-constructed Neco
data center is a must.

We should also consider install tools for efficient development, such as Telepresence.

When we deployed the application, sometimes the dctest k8s cluster became unstable. 
We also should investigate whether this problem occurs.

## Scope and goal

Define what is a must-have for launch and in-scope. Keep this section fluid and dynamic until you lock-in priority during planning.

## Definition of ready

- [ ] The epic owner is assigned.
- [ ] Initiatives and scopes are clearly stated.
- [ ] All necessary issues that complete this epic are created.
- [ ] At least three people agree on making this ready.
