### ISSUE TITLE
Support DSR with GENEVE

### ISSUE THREAD

**Issue by ysksuzuki** [cybozu-go/neco#2140]
## Description

Implement DSR with GENEVE in Cilium, and introduce it in our cluster.

## Initiative / Motivation

In the Cilium DSR mode, packets to loadbalancers reach to intermediate nodes, and Cilium selects a backend, stores Service IP and port in the IP options and redirects to the backend. But the reliance on IP options causes problem as follows.

- Linux kernel doesn't coalesce packets with IP options in GRO layer, and it can affect the packet processing performance
- There's a risk of packets with IP options being dropped by routers that do not support IP options and can parse the inner IP header

However, with the pure IPIP, which doesn't rely on the IP options, the service front port and backend port has to be the same, and that limitation is too restrictive for our use case since our tenant users have already deployed a lot of services with different service ports and backend ports. So we need to support  DSR with GENEVE, GUE (or other tunnels). With GENEVE or GUE, we can store the service IP and port, avoiding problems with the IP options.

## Technical information

Currently, Cilium doesn't support DSR mode, which doesn't rely on IP options for CNI setup.

## Scope and goal

We must have a DSR implementation which does not rely on IP options

## Definition of ready

- [x] The epic owner is assigned.
- [x] Initiatives and scopes are clearly stated.
- [x] Feasibility is proved by PoC or scrutiny.
- [x] All necessary issues that complete this epic are created.
- [x] At least three people (the epic owner and two other people) agree on making this ready.
