### ISSUE TITLE
Compatibility test for applications

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#215]
## Description

Users of Neco deploy applications on Kubernetes cluster build with [neco](https://github.com/cybozu-go/neco) and [neco-apps](https://github.com/cybozu-go/neco-apps).

We must guarantee backward compatibility for user applications.

## Initiative / Motivation

Describe how this Epic impacts an initiative the business is working on.

https://bozuman.cybozu.com/k/#/space/3801/thread/25931/1854831

## Scope and goal

Define what is a must-have for launch and in-scope. Keep this section fluid and dynamic until you lock-in priority during planning.

## Definition of ready

- [ ] The epic owner is assigned.
- [ ] Initiatives and scopes are clearly stated.
- [ ] All necessary issues that complete this epic are created.
- [ ] At least three people agree on making this ready.
