### ISSUE TITLE
Replace Cilium's MetalLB support with an alternative

### ISSUE THREAD

**Issue by ysksuzuki** [cybozu-go/neco#2157]
## Description

We're relying on Cilium's MetalLB support that announces LoadBalancer IPs of Services, but it will be deprecated in Cilium 1.13 and removed in 1.14 or later. Therefore, we need to transition to an alternative.
https://github.com/cilium/cilium/issues/22246

## Initiative / Motivation

Cilium's MetalLB support makes services to be accessible outside the cluster, and it's one of our critical components. So we need to move to a more stable and enhanced feature.

## Technical information

The possible options are

- Cilium's BGP Control plane LB-IPAM
  - The cilium team is working on implementing [LB-IPAM](https://github.com/cilium/cilium/pull/21764), and it's likely to be introduced in 1.13.
- [Standalone MetalLB](https://github.com/metallb/metallb)

## Scope and goal

Replace Cilium's MetalLB support with a stable and enhanced alternative

## Definition of ready

- [x] The epic owner is assigned.
- [ ] Initiatives and scopes are clearly stated.
- [ ] Feasibility is proved by PoC or scrutiny.
- [ ] All necessary issues that complete this epic are created.
- [ ] At least three people (the epic owner and two other people) agree on making this ready.

**Comment by yokaze** [comment]
moved to a private repository
