### ISSUE TITLE
Loki inter-cluster redundancy

### ISSUE THREAD

**Issue by umezawatakeshi** [cybozu-go/neco#2228]
## Description

make log store redundant by sending logs also to a foreign cluster.

## Initiative / Motivation

Ceph store in Neco cluster is not replicated by inter-cluster manner by CSA. We have to replicate Loki store by ourselves for now.

## Technical information

- Loki multi-tenancy https://grafana.com/docs/loki/latest/operations/multi-tenancy/
- fluent-bit https://docs.fluentbit.io/manual
  - We first evaluate fluent-bit as a replacement of promtail. We found that fluent-bit does not have enough feature for our purpose.

## Scope and goal

- enable Loki multi-tenant mode: one tenant for local pod logs, one tenant for foreign pod logs
- Send logs to the ceph object store in local and foreign cluster by another set of promtail

## Definition of ready

- [x] The epic owner is assigned.
- [x] Initiatives and scopes are clearly stated.
- [x] Feasibility is proved by PoC or scrutiny.
- [x] All necessary issues that complete this epic are created.
- [x] At least three people (the epic owner and two other people) agree on making this ready.
