### ISSUE TITLE
stage1 regular reboot

### ISSUE THREAD

**Issue by umezawatakeshi** [cybozu-go/neco#2233]
## What

add regular job (like cron job) to reboot all nodes every night.

## How

Describe how to address the issue.

## Checklist

- [x] Finish implementation of the issue
- [x] Test all functions
- [x] Have enough logs to trace activities
- [x] Notify developers of necessary actions

```[tasklist]
### Tasks
- [ ] https://github.com/cybozu-go/neco/pull/2637
```

**Comment by zeroalphat** [comment]
Implemented by https://github.com/cybozu-go/neco/pull/2637.
