### ISSUE TITLE
Enable sport-auto

### ISSUE THREAD

**Issue by ysksuzuki** [cybozu-go/neco#2269]
## Description

Let's fix the critical issues of coil-egress and make it more resilient

## Initiative / Motivation

Describe how this Epic impacts an initiative the business is working on.

## Technical information

Describe technical problems and possible solutions for this epic.

## Scope and goal

Define what is a must-have for launch and in-scope. Keep this section fluid and dynamic until you lock-in priority during planning.

## Definition of ready

- [ ] The epic owner is assigned.
- [ ] Initiatives and scopes are clearly stated.
- [ ] Feasibility is proved by PoC or scrutiny.
- [ ] All necessary issues that complete this epic are created.
- [ ] At least three people (the epic owner and two other people) agree on making this ready.

```[tasklist]
### Tasks
- [ ] https://github.com/cybozu-go/coil/issues/244
- [ ] https://github.com/cybozu-go/coil/issues/245
```

**Comment by yokaze** [comment]
done
