### ISSUE TITLE
[2023-12] Kubernetes 1.28

### ISSUE THREAD

**Issue by masa213f** [cybozu-go/neco#2348]
## Description

Update Neco for [Kubernetes 1.28](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md).
For reference, epic for 1.27 is #2297.

Submit conformance test results for Kubernetes 1.28 using [sonobuoy](https://github.com/vmware-tanzu/sonobuoy).
https://github.com/cncf/k8s-conformance/blob/master/instructions.md#uploading

Requirements for readiness:
- No [critical problems](https://github.com/kubernetes/kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3Apriority%2Fcritical-urgent).
- Applications running on neco are guaranteed working with kubernetes 1.28.

## Initiative / Motivation

We should update Kubernetes for each minor release.

## Technical information

T.B.D.

## Scope and goal

ref. https://neco.cybozu.wiki/procedure_k8s_upgrade/

## Definition of ready

- [x] The epic owner is assigned.
- [x] Initiatives and scopes are clearly stated.
- [x] Feasibility is proved by PoC or scrutiny.
- [x] All necessary issues that complete this epic are created.
- [x] At least three people agree on making this ready.

```[tasklist]
### Tasks
- [ ] https://github.com/cybozu-go/cke/issues/706
- [ ] https://github.com/cybozu-private/neco-tasks/issues/237
- [ ] https://github.com/cybozu-private/neco-tasks/issues/240
- [ ] https://github.com/cybozu-private/neco-tasks/issues/236
- [ ] https://github.com/cybozu-private/neco-tasks/issues/162
- [ ] https://github.com/cybozu-private/neco-tasks/issues/233
- [ ] https://github.com/cybozu-go/neco/issues/2513
- [ ] https://github.com/cybozu-private/neco-tasks/issues/238
- [ ] https://github.com/cybozu-private/neco-tasks/issues/239
- [ ] https://github.com/cybozu-private/neco-tasks/issues/241
```
