### ISSUE TITLE
Selective NAT for Kubernetes Pods

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#530]
## Description

Implement network-address-translation (NAT) for selected Kubernetes Pods.

## Initiative / Motivation

Although we have an HTTP(S) proxy for the Internet, some types of workloads can
be done nicely if Pods can access the Internet transparently.

Examples:
- cert-manager can do DNS01 authentication quicker if it can access DNS servers directly.
- Running dctest using [placemat](https://github.com/cybozu-go/placemat) in a Kubernetes Pod requires transparent access to the Internet.
- Connect MySQL servers running in another remote cluster or Forest from within Pod.

## Technical information

Assuming that the underlay network cannot help doing NAT only for some selected Pods,
the only way is to use some tunneling protocols such as [IP in IP](https://en.wikipedia.org/wiki/IP_in_IP) between the
source pod and NAT pod, where NAT pod is a pod having an IP address that can
reach the destination network.

Among others, [Foo over UDP (FOU)](https://lwn.net/Articles/614348/) or [Generic UDP Encapsulation (GUE)](https://lwn.net/Articles/615044/) look
the best because they encapsulate IP packets in UDP, and UDP can be load-balanced
nicely by Kubernetes Service.

Ref: [An introduction to Linux virtual interfaces: Tunnels](https://developers.redhat.com/blog/2019/05/17/an-introduction-to-linux-virtual-interfaces-tunnels/)

## Scope and goal

- NAT should be implemented as an extension of [Coil v2](#592).
- Only selected pods can do NAT.
- Multiple NAT gateways for different networks (Internet, Forest, remote Kubernetes, ...).
- High-availability of NAT gateways.

## Definition of ready

- [ ] The epic owner is assigned.
- [x] Initiatives and scopes are clearly stated.
- [x] Feasibility is proved by PoC or scrutiny.
- [ ] All necessary issues that complete this epic are created.
- [ ] At least three people agree on making this ready.

**Comment by ymmt2005** [comment]
PoC was done.  The result is available at https://gist.github.com/ymmt2005/f552ce8e424dd7f9cbc18920af921d46

**Comment by ymmt2005** [comment]
Will be done in #592
