### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by ymmt2005** [cybozu-go/neco#741]
## Description

Upgrade our Ubuntu images and procedures from 18.04 to 20.04.

## Initiative / Motivation

Ubuntu is used in boot servers and container base images in Neco.
Updating to the latest LTS releases is mandatory.

## Technical information

Ubuntu is [changing the installer](https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-2004-Server-Auto-Install), and therefore the new installer will not use [preseed](https://wiki.debian.org/DebianInstaller/Preseed).

- [Server installer plans for 20.04 LTS](https://discourse.ubuntu.com/t/server-installer-plans-for-20-04-lts/13631)
- [Automated Server Installs for 20.04](https://wiki.ubuntu.com/FoundationsTeam/AutomatedServerInstalls)
- [Pull request to implement the auto installer](https://github.com/CanonicalLtd/subiquity/pull/625)

## Scope and goal

- Create container base images based on Ubuntu 20.04.
    - Maintain both 18.04 and 20.04 container base images for the time being.
- Create ISO/QEMU custom installer of Ubuntu 20.04 for boot servers.
- Don't install `rkt` as it is no longer maintained.
    - Use Docker or something like that.
- Make sure we can smoothly upgrade the existing boot servers.
- Re-enable swtpm for placemat v2.

Non-scopes:
- Rebase container images against the new Ubuntu 20.04 base image.
    - Migrating from 18.04 to 20.04 should be done on other tasks.

## Definition of ready

- [ ] The epic owner is assigned.
- [x] Initiatives and scopes are clearly stated.
- [x] Feasibility is proved by PoC or scrutiny.
- [x] All necessary issues that complete this epic are created.
- [x] At least three people agree on making this ready.

**Comment by zoetrope** [comment]
LGTM
