### ISSUE TITLE
Design MySQL Operator

### ISSUE THREAD

**Issue by ysksuzuki** [cybozu-go/neco#885]
## Description

Find out failover procedures for certain failures by POC.

## Initiative / Motivation

In cybozu.com, MySQL is heavily used. But there is no MySQL operator that meets the requirements in the world. So we need to implement the operator.

## Technical information

Add as needed. (We need carefully consider the behavior during failover.)

## Scope and goal

- Write design documents covering failover procedures in which developers implement Operator with it. 
    - A failover caused by node failure needs to be automated at least
    - Failures that cannot be automated are handled manually and others are automated as much as possible
- Cover all failure patterns MySQL experts suggest

## Definition of ready

- [x] The epic owner is assigned.
- [x] Initiatives and scopes are clearly stated.
- [x] Feasibility is proved by PoC or scrutiny.
- [x] All important issues that complete this epic are created.
- [x] At least three people agree on making this ready.
